import { SAMPLE_PDF_DATA_URI, createInlineImage } from '../utils/preview'

export const SUPPLIER_TYPES = [
  { label: '原材料 / 外协外包类', value: 'raw' },
  { label: '配套件类', value: 'parts' },
  { label: '中间商类', value: 'trade' },
  { label: '技术合作类', value: 'tech' },
  { label: '运输类', value: 'transport' },
  { label: '其他类', value: 'other' },
]

export const PRODUCT_LEVELS = [
  { label: 'A 类产品', value: 'A' },
  { label: 'B 类产品', value: 'B' },
  { label: 'C 类产品', value: 'C' },
]

export const DOCUMENT_TYPES = [
  { label: '营业执照', value: 'business-license', accept: '.pdf,.png,.jpg,.jpeg' },
  { label: '质量管理体系证书', value: 'quality-system', accept: '.pdf,.png,.jpg,.jpeg' },
  { label: '行业强制认证', value: 'industry-cert', accept: '.pdf,.png,.jpg,.jpeg' },
  { label: '专利证书', value: 'patent-cert', accept: '.pdf,.png,.jpg,.jpeg' },
  { label: '其他资质', value: 'other', accept: '.pdf,.png,.jpg,.jpeg' },
]

export const STANDARD_FIELD_LIBRARY = {
  'business-license': ['企业名称', '统一社会信用代码', '法人', '证书有效期'],
  'quality-system': ['企业名称', '统一社会信用代码', '认证范围', '证书有效期'],
  'industry-cert': ['企业名称', '统一社会信用代码', '认证范围', '证书有效期'],
  'patent-cert': ['企业名称', '统一社会信用代码', '专利名称', '证书有效期'],
  other: ['企业名称', '统一社会信用代码', '证书有效期'],
}

export const THRESHOLD_MATRIX = {
  A: 90,
  B: 85,
  C: 80,
  tech: 85,
  transport: 80,
  other: 80,
}

export const MOCK_BUSINESS_REGISTRY = [
  {
    creditCode: '91440300MA5F8P2K2M',
    enterpriseName: '华锐精密制造（深圳）有限公司',
    legalPerson: '陈泽明',
    registerAddress: '深圳市南山区智造大道 88 号',
    status: '存续',
  },
  {
    creditCode: '91310000MA1K0A2B6Q',
    enterpriseName: '鼎衡供应链科技（上海）有限公司',
    legalPerson: '王承远',
    registerAddress: '上海市浦东新区云腾路 18 号',
    status: '存续',
  },
  {
    creditCode: '91440101MA59Q8T91H',
    enterpriseName: '晟远智造科技（广州）有限公司',
    legalPerson: '刘志远',
    registerAddress: '广州市黄埔区开源大道 66 号',
    status: '存续',
  },
  {
    creditCode: '91320115MA27L2C88P',
    enterpriseName: '筋云物流装备（南京）有限公司',
    legalPerson: '何嘉恒',
    registerAddress: '南京市江宁区星火路 12 号',
    status: '存续',
  },
  {
    creditCode: '91320594MA27B6N31K',
    enterpriseName: '启衡工业贸易（苏州）有限公司',
    legalPerson: '林岳',
    registerAddress: '苏州市工业园区金鸡湖大道 88 号',
    status: '存续',
  },
  {
    creditCode: '91500112MA61P8F54L',
    enterpriseName: '安澄环境服务（重庆）有限公司',
    legalPerson: '顾岩',
    registerAddress: '重庆市渝北区星光大道 16 号',
    status: '存续',
  },
]

export const STANDARD_TEMPLATES = [
  {
    id: 'std-raw-a-v3',
    name: '原材料/外协外包 A 类准入模板',
    version: 'V3.2',
    supplierType: 'raw',
    productLevel: 'A',
    status: '启用',
    threshold: 90,
    weights: {
      quality: 0.4,
      technical: 0.35,
      business: 0.25,
      bonusMax: 5,
    },
    requiredDocuments: ['business-license', 'quality-system', 'industry-cert'],
    recommendedDocuments: ['patent-cert', 'other'],
    vetoRules: ['技术能力不满足直接否决'],
  },
  {
    id: 'std-parts-b-v2',
    name: '配套件 B 类准入模板',
    version: 'V2.4',
    supplierType: 'parts',
    productLevel: 'B',
    status: '启用',
    threshold: 85,
    weights: {
      quality: 0.38,
      technical: 0.37,
      business: 0.25,
      bonusMax: 5,
    },
    requiredDocuments: ['business-license', 'quality-system', 'patent-cert'],
    recommendedDocuments: ['industry-cert', 'other'],
    vetoRules: ['设计能力或技术文件不满足直接否决'],
  },
  {
    id: 'std-tech-v1',
    name: '技术合作类通用模板',
    version: 'V1.8',
    supplierType: 'tech',
    productLevel: 'B',
    status: '启用',
    threshold: 85,
    weights: {
      quality: 0.3,
      technical: 0.45,
      business: 0.25,
      bonusMax: 5,
    },
    requiredDocuments: ['business-license', 'quality-system', 'patent-cert', 'other'],
    recommendedDocuments: ['industry-cert'],
    vetoRules: [],
  },
  {
    id: 'std-transport-c-v1',
    name: '运输类 C 级准入模板',
    version: 'V1.3',
    supplierType: 'transport',
    productLevel: 'C',
    status: '启用',
    threshold: 80,
    weights: {
      quality: 0.32,
      technical: 0.28,
      business: 0.4,
      bonusMax: 5,
    },
    requiredDocuments: ['business-license', 'industry-cert', 'patent-cert'],
    recommendedDocuments: ['other'],
    vetoRules: ['资质证书过期直接否决'],
  },
  {
    id: 'std-trade-b-v1',
    name: '贸易类 B 级准入模板',
    version: 'V1.5',
    supplierType: 'trade',
    productLevel: 'B',
    status: '启用',
    threshold: 84,
    weights: {
      quality: 0.3,
      technical: 0.2,
      business: 0.5,
      bonusMax: 5,
    },
    requiredDocuments: ['business-license', 'quality-system', 'other'],
    recommendedDocuments: ['industry-cert', 'patent-cert'],
    vetoRules: ['贸易代理授权链路缺失直接否决'],
  },
  {
    id: 'std-other-c-v1',
    name: '综合服务类 C 级准入模板',
    version: 'V1.1',
    supplierType: 'other',
    productLevel: 'C',
    status: '启用',
    threshold: 80,
    weights: {
      quality: 0.28,
      technical: 0.22,
      business: 0.5,
      bonusMax: 5,
    },
    requiredDocuments: ['business-license', 'other'],
    recommendedDocuments: ['quality-system', 'patent-cert'],
    vetoRules: ['服务承诺与安全责任函缺失直接否决'],
  },
]

export const KNOWLEDGE_BASE = [
  {
    id: 'faq-1',
    category: '风险预警',
    title: '证书过期后为什么会自动标记高风险？',
    summary: '系统会在机器预审阶段检查有效期，过期证书会直接加入风险列表并下调预审得分。',
    answer:
      '系统会在文件上传后先执行有效期校验、主体一致性校验和模板匹配校验。只要发现证书已过期，系统就会同步触发高风险标记、风险通知和后续重审提示，避免失效证书继续参与准入判断。',
    tags: ['证书有效期', '高风险', '自动预警'],
  },
  {
    id: 'faq-2',
    category: '审核结论',
    title: '为什么未通过的文件不能直接改状态？',
    summary: '需求规定未通过文件必须重新上传，保留历史记录可审计，避免审核轨迹被覆盖。',
    answer:
      '未通过结论对应的是一次完整审核动作，系统需要保留原始材料、审核意见和时间线。如果允许直接改状态，会破坏审计轨迹，也无法区分是“原问题已修复”还是“审核员手动覆盖”。因此正确流程是补传新材料，再进入新一轮审核或重审。',
    tags: ['未通过', '审计留痕', '重新上传'],
  },
  {
    id: 'faq-3',
    category: '账号与职责',
    title: '管理员可以修改供应商原始资料吗？',
    summary: '不可以。管理员只能审核和填写意见，原始资料与文件始终由供应商维护。',
    answer:
      '管理员在系统中的职责是审核、复核、风控和配置管理，不直接修改供应商原始填报内容。若发现资料错误，管理员可以发起补正通知、代上传补档文件或触发重审，但不会覆盖供应商提交的原始记录。',
    tags: ['管理员职责', '原始资料', '权限边界'],
  },
  {
    id: 'faq-4',
    category: '审核结论',
    title: '什么情况下会出现“有条件通过”？',
    summary: '当核心准入条件已满足，但仍存在需限期补充的条款或整改建议时，系统会标记为有条件通过。',
    answer:
      '“有条件通过”适用于供应商主体资格和核心资质已经满足准入要求，但某些佐证材料还需要在规定时间内补齐。例如说明函缺少盖章页、认证范围需要补充项目清单、承诺函缺少附页等。这类场景不直接否决，但会保留跟踪动作。',
    tags: ['有条件通过', '整改建议', '限期补件'],
  },
  {
    id: 'faq-5',
    category: '申诉与复核',
    title: '收到审核异议后，供应商如何发起申诉？',
    summary: '供应商可在结果与申诉中心查看未满足条款、整改建议及申诉截止时间，并按要求提交补充说明。',
    answer:
      '当审核记录被标记为可申诉时，供应商可以进入结果与申诉中心或申诉记录页，选择对应文件，填写申诉标题、详细说明、期望结果，并上传补充证据。提交后，管理员会在申诉复核台中受理并给出复核结论。',
    tags: ['申诉入口', '补充材料', '申诉流程'],
  },
  {
    id: 'faq-6',
    category: '注册填报',
    title: '统一社会信用代码查询没有回填成功怎么办？',
    summary: '先检查代码是否准确，再确认当前企业是否在 Mock 工商库中；未命中时可以手动填写。',
    answer:
      '当前系统使用的是前端 Mock 工商数据。若查询未命中，先确认统一社会信用代码位数和字符是否正确；若仍未命中，可以先手动填写企业信息并继续建档，管理员也可以在后续通过电子档案补充信息。',
    tags: ['统一社会信用代码', '工商回填', '手动补录'],
  },
  {
    id: 'faq-7',
    category: '文件上传',
    title: '补件后会重新排队审核，还是沿用原结论？',
    summary: '系统会保留原结论，同时为新补件生成新的审核或重审任务。',
    answer:
      '补件不会覆盖旧记录。系统会保留原审核结论，并将新上传文件作为新的审核对象进入待审核或重审流程。这样既能保留完整轨迹，也能让管理员对比前后材料差异。',
    tags: ['补件', '重审', '历史记录'],
  },
  {
    id: 'faq-8',
    category: '动态风控',
    title: '哪些情况下会自动触发复审或风控提醒？',
    summary: '证书临期、证书过期、主体信息不一致、同源命中、申诉积压等场景都会触发。',
    answer:
      '当前 Mock 规则会对证书临期 / 过期、认证范围待核实、主体名称不一致、同源主体命中、补件长期未完成和申诉积压等情况发出预警。命中高优先级规则时，还会直接进入风险处置队列，并可联动生成复审任务。',
    tags: ['动态风控', '复审触发', '规则命中'],
  },
  {
    id: 'faq-9',
    category: '案例库',
    title: '案例库适合拿来做什么？',
    summary: '案例库适合在正式上传前对照常见通过、补件、未通过场景做自查。',
    answer:
      '案例库展示的是典型审核结果样本，包括通过、有条件通过、未通过和申诉纠偏等场景。供应商可以在上传前对照同类型案例，提前准备缺失材料；管理员也可以把它当作培训和统一口径的参考样本。',
    tags: ['案例库', '自查', '培训样本'],
  },
]

export const CASE_LIBRARY = [
  {
    id: 'case-001',
    title: '原材料类营业执照与工商信息一致，直接审核通过',
    supplierType: 'raw',
    result: 'approved',
    caseCategory: '标准通过',
    summary: '营业执照、统一社会信用代码、法人信息和工商库完全一致，且文件清晰完整。',
    issueSummary: '无实质风险点，属于标准归档场景。',
    actions: ['核对企业名称与统一社会信用代码', '确认法人字段一致', '确认文件在有效期内'],
    takeaway: '主体类基础证照只要信息一致、清晰可辨，通常可直接进入归档。',
    relatedTemplateId: 'std-raw-a-v3',
    relatedFaqIds: ['faq-1', 'faq-6'],
    updatedAt: '2026-04-25T15:10:00',
  },
  {
    id: 'case-002',
    title: '质量体系证书缺少骑缝章，判定为有条件通过',
    supplierType: 'tech',
    result: 'conditional',
    caseCategory: '补件跟进',
    summary: '证书有效，主体信息正确，但末页缺少认证机构骑缝章，需要补充完整扫描件。',
    issueSummary: '材料核心有效，但附件完整性不足。',
    actions: ['保留有条件通过结论', '通知供应商补传盖章页', '进入后续跟踪清单'],
    takeaway: '对核心资质已满足但附件不完整的情况，优先使用“有条件通过 + 限期补件”而不是直接否决。',
    relatedTemplateId: 'std-tech-v1',
    relatedFaqIds: ['faq-4', 'faq-7'],
    updatedAt: '2026-04-22T15:18:00',
  },
  {
    id: 'case-003',
    title: '证书主体名称与工商登记不一致，审核未通过',
    supplierType: 'raw',
    result: 'rejected',
    caseCategory: '主体不一致',
    summary: '企业已经完成工商更名，但证书仍使用旧主体名称，且缺少认证机构出具的延续说明。',
    issueSummary: '主体连续性无法证明，存在较高合规风险。',
    actions: ['明确列出未满足条款', '要求补充更名证明与主体延续说明', '开放申诉入口'],
    takeaway: '凡是涉及主体变更的证书，都要同时核对工商变更证明和认证机构的连续性说明。',
    relatedTemplateId: 'std-raw-a-v3',
    relatedFaqIds: ['faq-2', 'faq-5'],
    updatedAt: '2026-04-24T16:40:00',
  },
  {
    id: 'case-004',
    title: '贸易类授权链路不完整，先保留结论并要求补件',
    supplierType: 'trade',
    result: 'conditional',
    caseCategory: '授权链路',
    summary: '品牌方到代理商的授权链路基本齐全，但末级代理盖章页缺失。',
    issueSummary: '授权关系存在缺口，无法形成完整责任闭环。',
    actions: ['保留有条件通过', '要求补充末级代理签章', '补充责任分界附件'],
    takeaway: '贸易类材料重点不只是主体证照，还要看授权链路是否真正闭环。',
    relatedTemplateId: 'std-trade-b-v1',
    relatedFaqIds: ['faq-4', 'faq-7'],
    updatedAt: '2026-04-26T08:50:00',
  },
  {
    id: 'case-005',
    title: '申诉补充更名材料后，未通过结论调整为通过',
    supplierType: 'parts',
    result: 'approved',
    caseCategory: '申诉纠偏',
    summary: '供应商补充新版证书、工商变更证明和主体连续性说明后，申诉成立并恢复通过。',
    issueSummary: '初审信息不足，但后续证据补强充分。',
    actions: ['申诉受理', '核对新版证书与工商变更信息', '调整原审核结论并回传结果'],
    takeaway: '申诉并不是重复提交，而是针对初审证据不足场景的纠偏机制。',
    relatedTemplateId: 'std-parts-b-v2',
    relatedFaqIds: ['faq-5', 'faq-9'],
    updatedAt: '2026-04-16T18:10:00',
  },
]

export const MOCK_SUPPLIERS = [
  {
    id: 'sup-001',
    account: 'supplier01',
    password: '123456',
    registeredAt: '2026-01-06T10:00:00',
    enterprise: {
      enterpriseName: '华锐精密制造（深圳）有限公司',
      creditCode: '91440300MA5F8P2K2M',
      legalPerson: '陈泽明',
      contactName: '李雨桐',
      contactPhone: '13800138000',
      registerAddress: '深圳市南山区智造大道 88 号',
      productionAddress: '深圳市宝安区智造园 6 栋',
      foundedAt: '2018-05-12',
      registeredCapital: '3000 万人民币',
      businessScope: '精密零件加工、机加工件制造、供应链协同服务',
      supplierType: 'raw',
      productLevel: 'A',
      templateId: 'std-raw-a-v3',
      greenCertified: true,
    },
    teamMembers: [
      { name: '陈泽明', role: '法人', idNo: '440301198901013216' },
      { name: '赵文博', role: '质量负责人', idNo: '440301198711126812' },
    ],
    relatedParties: [
      { name: '陈泽明', relation: '法人', idNo: '440301198901013216' },
      { name: '王承远', relation: '战略股东', idNo: '310101198805150021' },
    ],
    changeHistory: [
      {
        id: 'chg-001',
        at: '2026-03-02T09:20:00',
        field: '生产地址',
        from: '深圳市宝安区旧厂房 2 号',
        to: '深圳市宝安区智造园 6 栋',
      },
    ],
  },
  {
    id: 'sup-002',
    account: 'cloud02',
    password: '123456',
    registeredAt: '2026-02-15T09:30:00',
    enterprise: {
      enterpriseName: '鼎衡供应链科技（上海）有限公司',
      creditCode: '91310000MA1K0A2B6Q',
      legalPerson: '王承远',
      contactName: '周奕辰',
      contactPhone: '13922334455',
      registerAddress: '上海市浦东新区云腾路 18 号',
      productionAddress: '上海市嘉定区智联产业园 9 号',
      foundedAt: '2019-09-18',
      registeredCapital: '1500 万人民币',
      businessScope: '供应链服务、物流方案、配套件采购',
      supplierType: 'parts',
      productLevel: 'B',
      templateId: 'std-parts-b-v2',
      greenCertified: false,
    },
    teamMembers: [
      { name: '王承远', role: '法人', idNo: '310101198805150021' },
      { name: '周奕辰', role: '商务负责人', idNo: '310101199105083613' },
    ],
    relatedParties: [{ name: '王承远', relation: '法人', idNo: '310101198805150021' }],
    changeHistory: [],
  },
  {
    id: 'sup-003',
    account: 'tech03',
    password: '123456',
    registeredAt: '2026-03-08T15:20:00',
    enterprise: {
      enterpriseName: '晟远智造科技（广州）有限公司',
      creditCode: '91440101MA59Q8T91H',
      legalPerson: '刘志远',
      contactName: '林若岚',
      contactPhone: '13677889900',
      registerAddress: '广州市黄埔区开源大道 66 号',
      productionAddress: '广州市增城区智造园 3 栋',
      foundedAt: '2020-04-08',
      registeredCapital: '2000 万人民币',
      businessScope: '工业视觉检测设备、自动化夹具、技术协同开发服务',
      supplierType: 'tech',
      productLevel: 'B',
      templateId: 'std-tech-v1',
      greenCertified: true,
    },
    teamMembers: [
      { name: '刘志远', role: '法人', idNo: '440101198710068833' },
      { name: '林若岚', role: '项目经理', idNo: '440101199204120056' },
    ],
    relatedParties: [
      { name: '刘志远', relation: '法人', idNo: '440101198710068833' },
      { name: '王承远', relation: '战略顾问', idNo: '310101198805150021' },
    ],
    changeHistory: [
      {
        id: 'chg-003',
        at: '2026-04-10T11:10:00',
        field: '经营范围',
        from: '工业视觉检测设备、自动化夹具',
        to: '工业视觉检测设备、自动化夹具、技术协同开发服务',
      },
    ],
  },
  {
    id: 'sup-004',
    account: 'logistics04',
    password: '123456',
    registeredAt: '2026-03-22T08:45:00',
    enterprise: {
      enterpriseName: '筋云物流装备（南京）有限公司',
      creditCode: '91320115MA27L2C88P',
      legalPerson: '何嘉恒',
      contactName: '许晋安',
      contactPhone: '13766554433',
      registerAddress: '南京市江宁区星火路 12 号',
      productionAddress: '南京市江宁区云轨产业园 1 号库',
      foundedAt: '2021-02-19',
      registeredCapital: '1200 万人民币',
      businessScope: '物流周转器具、运输周转箱、仓储配套设备制造与维护',
      supplierType: 'transport',
      productLevel: 'C',
      templateId: 'std-transport-c-v1',
      greenCertified: false,
    },
    teamMembers: [
      { name: '何嘉恒', role: '法人', idNo: '320101199610100018' },
      { name: '许晋安', role: '仓储负责人', idNo: '320101199307180045' },
    ],
    relatedParties: [{ name: '何嘉恒', relation: '法人', idNo: '320101199610100018' }],
    changeHistory: [],
  },
  {
    id: 'sup-005',
    account: 'trade05',
    password: '123456',
    registeredAt: '2026-04-05T13:40:00',
    enterprise: {
      enterpriseName: '启衡工业贸易（苏州）有限公司',
      creditCode: '91320594MA27B6N31K',
      legalPerson: '林岳',
      contactName: '许澄',
      contactPhone: '13588997766',
      registerAddress: '苏州市工业园区金鸡湖大道 88 号',
      productionAddress: '苏州市相城区供应链协同仓 2 号库',
      foundedAt: '2020-11-03',
      registeredCapital: '1800 万人民币',
      businessScope: '工业品贸易、供应链协同、代理采购与质量追溯服务',
      supplierType: 'trade',
      productLevel: 'B',
      templateId: 'std-trade-b-v1',
      greenCertified: false,
    },
    teamMembers: [
      { name: '林岳', role: '法人', idNo: '320501198909180027' },
      { name: '许澄', role: '商务负责人', idNo: '320501199402142619' },
    ],
    relatedParties: [{ name: '林岳', relation: '法人', idNo: '320501198909180027' }],
    changeHistory: [
      {
        id: 'chg-005',
        at: '2026-04-16T09:35:00',
        field: '联系人手机号',
        from: '13588990011',
        to: '13588997766',
      },
    ],
  },
  {
    id: 'sup-006',
    account: 'service06',
    password: '123456',
    registeredAt: '2026-04-09T10:05:00',
    enterprise: {
      enterpriseName: '安澄环境服务（重庆）有限公司',
      creditCode: '91500112MA61P8F54L',
      legalPerson: '顾岩',
      contactName: '周岚',
      contactPhone: '13455667788',
      registerAddress: '重庆市渝北区星光大道 16 号',
      productionAddress: '重庆市两江新区环保服务中心 5 层',
      foundedAt: '2021-07-15',
      registeredCapital: '900 万人民币',
      businessScope: '园区环保运维、危废协同管理、现场驻场服务',
      supplierType: 'other',
      productLevel: 'C',
      templateId: 'std-other-c-v1',
      greenCertified: true,
    },
    teamMembers: [
      { name: '顾岩', role: '法人', idNo: '500101198803210032' },
      { name: '周岚', role: '项目经理', idNo: '500101199112054826' },
    ],
    relatedParties: [{ name: '顾岩', relation: '法人', idNo: '500101198803210032' }],
    changeHistory: [],
  },
]

export const MOCK_ADMINS = [
  {
    id: 'adm-001',
    account: 'admin',
    password: 'admin123',
    name: '采购审核员-周岚',
    role: 'reviewer',
    roleLabel: '采购/审核员',
    status: 'active',
    phone: '13900139001',
    email: 'zhoulan.audit@example.com',
    lastLoginAt: '2026-04-29T09:20:00',
    dataScope: '审核业务范围',
    permissions: ['reviews', 'appeals', 'rereviews', 'risk-radar', 'suppliers', 'logs'],
  },
  {
    id: 'adm-002',
    account: 'sysadmin',
    password: 'sysadmin123',
    name: '系统管理员-许宁',
    role: 'system-admin',
    roleLabel: '系统管理员',
    status: 'active',
    phone: '13900139009',
    email: 'xuning.admin@example.com',
    lastLoginAt: '2026-04-29T18:45:00',
    dataScope: '全局系统配置',
    permissions: ['reviews', 'appeals', 'rereviews', 'risk-radar', 'suppliers', 'standards', 'logs', 'permissions', 'integrations'],
  },
]

export const MOCK_REVIEW_LOGS = [
  {
    id: 'log-001',
    recordId: 'doc-001',
    taskNo: 'WK-202604-0001',
    supplierName: '华锐精密制造（深圳）有限公司',
    fileName: '营业执照-最新版.pdf',
    reviewer: '采购审核员-周岚',
    action: '审核通过',
    result: '已通过',
    score: 94,
    comment: '证照信息完整，企业信息与工商库一致。',
    reviewedAt: '2026-04-03T14:20:00',
  },
  {
    id: 'log-002',
    recordId: 'doc-005',
    taskNo: 'WK-202604-0005',
    supplierName: '华锐精密制造（深圳）有限公司',
    fileName: '行业强制认证-补充说明版.pdf',
    reviewer: '采购审核员-周岚',
    action: '审核有条件通过',
    result: '有条件通过',
    score: 89,
    comment: '证书主体有效，但补充说明仍需在 5 个工作日内补齐盖章页。',
    reviewedAt: '2026-04-18T17:10:00',
  },
  {
    id: 'log-003',
    recordId: 'doc-006',
    taskNo: 'WK-202604-0006',
    supplierName: '晟远智造科技（广州）有限公司',
    fileName: '营业执照-管理员代上传.pdf',
    reviewer: '采购审核员-周岚',
    action: '审核通过',
    result: '已通过',
    score: 91,
    comment: '管理员代上传的营业执照与工商库信息一致，可直接归档。',
    reviewedAt: '2026-04-21T10:30:00',
  },
  {
    id: 'log-004',
    recordId: 'doc-007',
    taskNo: 'WK-202604-0007',
    supplierName: '晟远智造科技（广州）有限公司',
    fileName: '质量体系证书-待补章.pdf',
    reviewer: '采购审核员-周岚',
    action: '审核有条件通过',
    result: '有条件通过',
    score: 86,
    comment: '证书有效，但末页缺少认证机构骑缝章，需要补充后归档。',
    reviewedAt: '2026-04-22T15:18:00',
  },
  {
    id: 'log-005',
    recordId: 'doc-009',
    taskNo: 'WK-202604-0009',
    supplierName: '华锐精密制造（深圳）有限公司',
    fileName: '质量体系证书-更名说明版.pdf',
    reviewer: '采购审核员 周岚',
    action: '审核未通过',
    result: '未通过',
    score: 78,
    comment: '证书主体名称与工商登记不一致，当前更名说明缺少原认证机构补充确认函。',
    reviewedAt: '2026-04-24T16:40:00',
  },
  {
    id: 'log-006',
    recordId: 'doc-010',
    taskNo: 'WK-202604-0010',
    supplierName: '华锐精密制造（深圳）有限公司',
    fileName: '补充说明函-采购范围核验.pdf',
    reviewer: '采购审核员 周岚',
    action: '审核有条件通过',
    result: '有条件通过',
    score: 84,
    comment: '补充说明已提交，但未明确覆盖全部采购件型，允许先行保留结果并继续补强。',
    reviewedAt: '2026-04-25T11:25:00',
  },
  {
    id: 'log-007',
    recordId: 'doc-011',
    taskNo: 'WK-202604-0011',
    supplierName: '筋云物流装备（南京）有限公司',
    fileName: '营业执照-管理员批次补档.pdf',
    reviewer: '采购审核员 周岚',
    action: '审核通过',
    result: '已通过',
    score: 92,
    comment: '批量代上传补档资料完整，适合作为运输类供应商集中建档示例。',
    reviewedAt: '2026-04-25T15:10:00',
  },
  {
    id: 'log-008',
    recordId: 'doc-013',
    taskNo: 'WK-202604-0013',
    supplierName: '安澄环境服务（重庆）有限公司',
    fileName: '安全责任承诺函-管理员批次上传.pdf',
    reviewer: '采购审核员 周岚',
    action: '审核通过',
    result: '已通过',
    score: 88,
    comment: '综合服务类批量补档已完成，责任承诺函内容齐全。',
    reviewedAt: '2026-04-25T15:36:00',
  },
]

export const MOCK_NOTIFICATION_LOGS = [
  {
    id: 'msg-001',
    recordId: 'doc-002',
    supplierId: 'sup-001',
    supplierName: '华锐精密制造（深圳）有限公司',
    fileName: '质量体系证书-2026版.pdf',
    phone: '13800138000',
    channel: 'sms',
    mode: 'auto',
    trigger: 'upload-auto',
    operatorName: '系统',
    riskLabel: '重点关注',
    alertLabels: ['证书临期', '认证范围待核实'],
    message:
      '【供应商资质助手】贵司文件《质量体系证书-2026版.pdf》存在重点关注告警：证书临期、认证范围待核实。请尽快登录系统查看并处理。',
    status: 'sent',
    sentAt: '2026-04-15T09:45:00',
  },
  {
    id: 'msg-002',
    recordId: 'doc-004',
    supplierId: 'sup-002',
    supplierName: '鼎衡供应链科技（上海）有限公司',
    fileName: '行业强制认证-已过期.pdf',
    phone: '13922334455',
    channel: 'sms',
    mode: 'auto',
    trigger: 'upload-auto',
    operatorName: '系统',
    riskLabel: '紧急处理',
    alertLabels: ['证书已过期'],
    message:
      '【供应商资质助手】贵司文件《行业强制认证-已过期.pdf》存在紧急处理告警：证书已过期。请立即补传最新有效文件。',
    status: 'sent',
    sentAt: '2026-04-20T10:28:00',
  },
  {
    id: 'msg-003',
    recordId: 'doc-005',
    supplierId: 'sup-001',
    supplierName: '华锐精密制造（深圳）有限公司',
    fileName: '行业强制认证-补充说明版.pdf',
    phone: '13800138000',
    channel: 'sms',
    mode: 'manual',
    trigger: 'manual',
    operatorName: '采购审核员-周岚',
    riskLabel: '重点关注',
    alertLabels: ['认证范围待核实', '待人工复核'],
    message:
      '【供应商资质助手】贵司文件《行业强制认证-补充说明版.pdf》审核结论为有条件通过，请在申诉/结果中心查看未满足条款和补充要求。',
    status: 'sent',
    sentAt: '2026-04-18T17:15:00',
  },
  {
    id: 'msg-004',
    recordId: 'doc-007',
    supplierId: 'sup-003',
    supplierName: '晟远智造科技（广州）有限公司',
    fileName: '质量体系证书-待补章.pdf',
    phone: '13677889900',
    channel: 'sms',
    mode: 'auto',
    trigger: 'review-auto',
    operatorName: '系统',
    riskLabel: '跟进观察',
    alertLabels: ['待人工复核'],
    message:
      '【供应商资质助手】贵司文件《质量体系证书-待补章.pdf》已形成有条件通过结论，请按整改建议补充材料。',
    status: 'sent',
    sentAt: '2026-04-22T15:20:00',
  },
  {
    id: 'msg-005',
    recordId: 'doc-009',
    supplierId: 'sup-001',
    supplierName: '华锐精密制造（深圳）有限公司',
    fileName: '质量体系证书-更名说明版.pdf',
    phone: '13800138000',
    channel: 'sms',
    mode: 'manual',
    trigger: 'manual',
    operatorName: '采购审核员 周岚',
    riskLabel: '高风险待处理',
    alertLabels: ['主体信息不一致', '待人工复核'],
    batchNo: 'BATCH-NOTICE-20260426-01',
    message:
      '【供应商资质助手】贵司文件《质量体系证书-更名说明版.pdf》审核未通过，已纳入批量提醒，请尽快在结果中心查看未满足条款和申诉说明。',
    status: 'sent',
    sentAt: '2026-04-26T09:20:00',
  },
  {
    id: 'msg-006',
    recordId: 'doc-012',
    supplierId: 'sup-005',
    supplierName: '启衡工业贸易（苏州）有限公司',
    fileName: '代理授权链路说明函.pdf',
    phone: '13588997766',
    channel: 'sms',
    mode: 'manual',
    trigger: 'manual',
    operatorName: '采购审核员 周岚',
    riskLabel: '重点关注',
    alertLabels: ['认证范围待核实', '待人工复核'],
    batchNo: 'BATCH-NOTICE-20260426-01',
    message:
      '【供应商资质助手】贵司文件《代理授权链路说明函.pdf》已进入重点关注批量提醒，请补充完整授权链路后再次提交审核。',
    status: 'sent',
    sentAt: '2026-04-26T09:22:00',
  },
  {
    id: 'msg-007',
    recordId: 'doc-014',
    supplierId: 'sup-006',
    supplierName: '安澄环境服务（重庆）有限公司',
    fileName: '驻场服务安全责任函-补传版.pdf',
    phone: '13455667788',
    channel: 'sms',
    mode: 'manual',
    trigger: 'manual',
    operatorName: '采购审核员 周岚',
    riskLabel: '重点关注',
    alertLabels: ['补传资料待确认'],
    batchNo: 'BATCH-NOTICE-20260426-01',
    message:
      '【供应商资质助手】贵司文件《驻场服务安全责任函-补传版.pdf》已收到管理员批量通知，请尽快查看补传要求并跟进。',
    status: 'sent',
    sentAt: '2026-04-26T09:24:00',
  },
]

export const MOCK_DOCUMENTS = [
  {
    id: 'doc-001',
    taskNo: 'WK-202604-0001',
    supplierId: 'sup-001',
    fileName: '营业执照-最新版.pdf',
    category: 'business-license',
    mimeType: 'application/pdf',
    sizeMB: 2.6,
    uploadedAt: '2026-04-03T11:18:00',
    status: 'approved',
    machineStatus: 'pass',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-raw-a-v3',
    extractedFields: {
      enterpriseName: '华锐精密制造（深圳）有限公司',
      creditCode: '91440300MA5F8P2K2M',
      legalPerson: '陈泽明',
      validUntil: '2029-12-31',
      certificationScope: '企业主体经营资格',
    },
    comparisons: [
      { field: '企业名称', expected: '华锐精密制造（深圳）有限公司', actual: '华锐精密制造（深圳）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91440300MA5F8P2K2M', actual: '91440300MA5F8P2K2M', result: '匹配' },
      { field: '法人', expected: '陈泽明', actual: '陈泽明', result: '匹配' },
      { field: '证书有效期', expected: '有效', actual: '2029-12-31', result: '匹配' },
    ],
    riskFlags: [],
    precheckScore: 94,
    scoreBreakdown: { quality: 93, technical: 92, business: 94, bonus: 4, total: 94 },
    sameSourceMatches: [{ matchedCompany: '鼎衡供应链科技（上海）有限公司', person: '王承远', relation: '战略股东', riskLevel: '中' }],
    adminOpinion: '证照真实有效，通过。',
    unmetClauses: [],
    improvementSuggestions: [],
    appealable: false,
    appealDeadline: '',
    reviewerName: '采购审核员-周岚',
    reviewedAt: '2026-04-03T14:20:00',
  },
  {
    id: 'doc-002',
    taskNo: 'WK-202604-0002',
    supplierId: 'sup-001',
    fileName: '质量体系证书-2026版.pdf',
    category: 'quality-system',
    mimeType: 'application/pdf',
    sizeMB: 3.2,
    uploadedAt: '2026-04-15T09:42:00',
    status: 'pending',
    machineStatus: 'warning',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-raw-a-v3',
    extractedFields: {
      enterpriseName: '华锐精密制造（深圳）有限公司',
      creditCode: '91440300MA5F8P2K2M',
      legalPerson: '陈泽明',
      validUntil: '2026-05-20',
      certificationScope: '机加工件质量管理体系',
    },
    comparisons: [
      { field: '企业名称', expected: '华锐精密制造（深圳）有限公司', actual: '华锐精密制造（深圳）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91440300MA5F8P2K2M', actual: '91440300MA5F8P2K2M', result: '匹配' },
      { field: '认证范围', expected: '应覆盖机加工件制造', actual: '机加工件质量管理体系', result: '待确认' },
      { field: '证书有效期', expected: '有效', actual: '2026-05-20', result: '待确认' },
    ],
    riskFlags: ['证书接近到期', '认证范围需要人工确认'],
    externalChecks: [
      {
        id: 'ext-doc-002-1',
        serviceCode: 'ocr-engine',
        serviceName: 'OCR 识别服务',
        checkItem: '质量体系证书字段识别',
        materialName: '质量体系证书-2026版.pdf',
        affectedFields: ['认证范围', '证书有效期'],
        affectedMaterials: ['质量体系证书-2026版.pdf'],
        status: 'exception',
        exceptionType: 'timeout',
        message: 'OCR 识别服务调用超时，未返回完整结构化字段。',
        fallbackSuggestion: '请人工核对证书中的认证范围、有效期和认证机构信息。',
      },
      {
        id: 'ext-doc-002-2',
        serviceCode: 'certificate-platform',
        serviceName: '证书验真平台',
        checkItem: '证书真伪核验',
        materialName: '质量体系证书-2026版.pdf',
        affectedFields: ['证书编号', '有效期'],
        affectedMaterials: ['质量体系证书-2026版.pdf'],
        status: 'exception',
        exceptionType: 'no-response',
        message: '证书验真平台暂时无响应，未返回验真结果。',
        fallbackSuggestion: '请结合原始扫描件、证书编号和有效期进行人工确认。',
      },
    ],
    precheckScore: 87,
    scoreBreakdown: { quality: 85, technical: 89, business: 86, bonus: 4, total: 87 },
    sameSourceMatches: [{ matchedCompany: '鼎衡供应链科技（上海）有限公司', person: '王承远', relation: '战略股东', riskLevel: '中' }],
    adminOpinion: '',
    unmetClauses: [],
    improvementSuggestions: [],
    appealable: false,
    appealDeadline: '',
    reviewerName: '',
    reviewedAt: '',
  },
  {
    id: 'doc-003',
    taskNo: 'WK-202604-0003',
    supplierId: 'sup-002',
    fileName: '专利证书-信息不一致.png',
    category: 'patent-cert',
    mimeType: 'image/png',
    sizeMB: 1.1,
    uploadedAt: '2026-04-12T13:15:00',
    status: 'rejected',
    machineStatus: 'fail',
    previewUrl: createInlineImage('专利证书-信息不一致', '#c33f22'),
    standardTemplateId: 'std-parts-b-v2',
    extractedFields: {
      enterpriseName: '鼎衡供应链科技（上海）有限公司（旧）',
      creditCode: '91310000MA1K0A2B6Q',
      legalPerson: '王承远',
      validUntil: '2027-12-01',
      certificationScope: '配套件结构优化专利',
    },
    comparisons: [
      { field: '企业名称', expected: '鼎衡供应链科技（上海）有限公司', actual: '鼎衡供应链科技（上海）有限公司（旧）', result: '不匹配' },
      { field: '统一社会信用代码', expected: '91310000MA1K0A2B6Q', actual: '91310000MA1K0A2B6Q', result: '匹配' },
      { field: '专利名称', expected: '需与技术申报一致', actual: '配套件结构优化专利', result: '待确认' },
      { field: '证书有效期', expected: '有效', actual: '2027-12-01', result: '匹配' },
    ],
    riskFlags: ['企业名称与工商登记不一致'],
    precheckScore: 72,
    scoreBreakdown: { quality: 70, technical: 74, business: 72, bonus: 0, total: 72 },
    sameSourceMatches: [],
    adminOpinion: '企业名称与登记信息不一致，请重新上传最新证书。',
    unmetClauses: ['企业名称与登记信息不一致'],
    improvementSuggestions: ['请上传最新版本专利证书', '保持证书主体名称与供应商主数据一致'],
    appealable: true,
    appealDeadline: '2026-05-06T23:59:59',
    appealSceneTitle: '证书主体更名异议',
    appealSceneSummary: '适用于供应商认为证书主体名称差异源于更名过渡，准备补充更名证明、认证机构说明函后发起申诉。',
    reviewerName: '采购审核员-周岚',
    reviewedAt: '2026-04-12T16:05:00',
  },
  {
    id: 'doc-004',
    taskNo: 'WK-202604-0004',
    supplierId: 'sup-002',
    fileName: '行业强制认证-已过期.pdf',
    category: 'industry-cert',
    mimeType: 'application/pdf',
    sizeMB: 2.8,
    uploadedAt: '2026-04-20T10:25:00',
    status: 'pending',
    machineStatus: 'fail',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-parts-b-v2',
    extractedFields: {
      enterpriseName: '鼎衡供应链科技（上海）有限公司',
      creditCode: '91310000MA1K0A2B6Q',
      legalPerson: '王承远',
      validUntil: '2025-12-31',
      certificationScope: '配套件行业强制认证',
    },
    comparisons: [
      { field: '企业名称', expected: '鼎衡供应链科技（上海）有限公司', actual: '鼎衡供应链科技（上海）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91310000MA1K0A2B6Q', actual: '91310000MA1K0A2B6Q', result: '匹配' },
      { field: '认证范围', expected: '应覆盖配套件制造', actual: '配套件行业强制认证', result: '待确认' },
      { field: '证书有效期', expected: '有效', actual: '2025-12-31', result: '不匹配' },
    ],
    riskFlags: ['证书已过期'],
    precheckScore: 68,
    scoreBreakdown: { quality: 62, technical: 70, business: 72, bonus: 0, total: 68 },
    sameSourceMatches: [],
    adminOpinion: '',
    unmetClauses: [],
    improvementSuggestions: [],
    appealable: false,
    appealDeadline: '',
    reviewerName: '',
    reviewedAt: '',
  },
  {
    id: 'doc-005',
    taskNo: 'WK-202604-0005',
    supplierId: 'sup-001',
    fileName: '行业强制认证-补充说明版.pdf',
    category: 'industry-cert',
    mimeType: 'application/pdf',
    sizeMB: 2.4,
    uploadedAt: '2026-04-18T14:08:00',
    status: 'conditional',
    machineStatus: 'warning',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-raw-a-v3',
    extractedFields: {
      enterpriseName: '华锐精密制造（深圳）有限公司',
      creditCode: '91440300MA5F8P2K2M',
      legalPerson: '陈泽明',
      validUntil: '2027-11-30',
      certificationScope: '机加工件行业强制认证',
    },
    comparisons: [
      { field: '企业名称', expected: '华锐精密制造（深圳）有限公司', actual: '华锐精密制造（深圳）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91440300MA5F8P2K2M', actual: '91440300MA5F8P2K2M', result: '匹配' },
      { field: '认证范围', expected: '应覆盖机加工件制造', actual: '机加工件行业强制认证', result: '待确认' },
      { field: '证书有效期', expected: '有效', actual: '2027-11-30', result: '匹配' },
    ],
    riskFlags: ['认证范围需要人工确认'],
    precheckScore: 89,
    scoreBreakdown: { quality: 88, technical: 90, business: 87, bonus: 4, total: 89 },
    sameSourceMatches: [{ matchedCompany: '鼎衡供应链科技（上海）有限公司', person: '王承远', relation: '战略股东', riskLevel: '中' }],
    adminOpinion: '证书主体有效，但补充说明仍需在 5 个工作日内补齐盖章页。',
    unmetClauses: ['认证机构盖章页缺失', '补充说明未明确覆盖本次采购产品范围'],
    improvementSuggestions: ['补传带完整盖章页的认证附件', '在补充说明中明确覆盖采购件型号范围'],
    appealable: true,
    appealDeadline: '2026-05-10T23:59:59',
    appealSceneTitle: '认证范围补充说明申诉',
    appealSceneSummary: '适用于供应商已具备核心资质，但认为补充说明能够覆盖采购件型，准备上传盖章说明与历史供货佐证。',
    reviewerName: '采购审核员-周岚',
    reviewedAt: '2026-04-18T17:10:00',
  },
  {
    id: 'doc-006',
    taskNo: 'WK-202604-0006',
    supplierId: 'sup-003',
    fileName: '营业执照-管理员代上传.pdf',
    category: 'business-license',
    mimeType: 'application/pdf',
    sizeMB: 1.9,
    uploadedAt: '2026-04-21T09:12:00',
    status: 'approved',
    machineStatus: 'pass',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-tech-v1',
    extractedFields: {
      enterpriseName: '晟远智造科技（广州）有限公司',
      creditCode: '91440101MA59Q8T91H',
      legalPerson: '刘志远',
      validUntil: '2029-08-31',
      certificationScope: '企业主体经营资格',
    },
    comparisons: [
      { field: '企业名称', expected: '晟远智造科技（广州）有限公司', actual: '晟远智造科技（广州）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91440101MA59Q8T91H', actual: '91440101MA59Q8T91H', result: '匹配' },
      { field: '法人', expected: '刘志远', actual: '刘志远', result: '匹配' },
      { field: '证书有效期', expected: '有效', actual: '2029-08-31', result: '匹配' },
    ],
    riskFlags: [],
    precheckScore: 91,
    scoreBreakdown: { quality: 90, technical: 90, business: 92, bonus: 4, total: 91 },
    sameSourceMatches: [{ matchedCompany: '鼎衡供应链科技（上海）有限公司', person: '王承远', relation: '战略顾问', riskLevel: '中' }],
    adminOpinion: '管理员代上传资料齐全，营业执照可直接归档。',
    unmetClauses: [],
    improvementSuggestions: [],
    appealable: false,
    appealDeadline: '',
    reviewerName: '采购审核员-周岚',
    reviewedAt: '2026-04-21T10:30:00',
    batchNo: 'BATCH-UP-20260422-01',
    uploadSource: 'admin',
    uploadedByRole: 'admin',
    uploadedByName: '采购审核员-周岚',
  },
  {
    id: 'doc-007',
    taskNo: 'WK-202604-0007',
    supplierId: 'sup-003',
    fileName: '质量体系证书-待补章.pdf',
    category: 'quality-system',
    mimeType: 'application/pdf',
    sizeMB: 3.6,
    uploadedAt: '2026-04-22T11:42:00',
    status: 'conditional',
    machineStatus: 'warning',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-tech-v1',
    extractedFields: {
      enterpriseName: '晟远智造科技（广州）有限公司',
      creditCode: '91440101MA59Q8T91H',
      legalPerson: '刘志远',
      validUntil: '2026-08-15',
      certificationScope: '自动化检测设备质量管理体系',
    },
    comparisons: [
      { field: '企业名称', expected: '晟远智造科技（广州）有限公司', actual: '晟远智造科技（广州）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91440101MA59Q8T91H', actual: '91440101MA59Q8T91H', result: '匹配' },
      { field: '认证范围', expected: '应覆盖机加工件制造', actual: '自动化检测设备质量管理体系', result: '待确认' },
      { field: '证书有效期', expected: '有效', actual: '2026-08-15', result: '待确认' },
    ],
    riskFlags: ['证书接近到期', '认证范围需要人工确认'],
    externalChecks: [
      {
        id: 'ext-doc-007-1',
        serviceCode: 'ocr-engine',
        serviceName: 'OCR 识别服务',
        checkItem: '体系证书字段识别',
        materialName: '质量体系证书-待补章.pdf',
        affectedFields: ['认证范围', '盖章页'],
        affectedMaterials: ['质量体系证书-待补章.pdf'],
        status: 'manual-reviewed',
        exceptionType: 'partial-result',
        message: 'OCR 识别结果缺少末页盖章区域，未形成完整识别快照。',
        fallbackSuggestion: '请人工核对末页盖章情况，并结合证书原件确认。',
        manualDecision: 'risk-retained',
        manualNote: '已人工核对主体和有效期，确认主要风险在于末页盖章缺失，保留有条件通过并要求补件。',
        handledAt: '2026-04-22T15:18:00',
        handledBy: '采购审核员-周岚',
      },
    ],
    precheckScore: 86,
    scoreBreakdown: { quality: 84, technical: 88, business: 85, bonus: 4, total: 86 },
    sameSourceMatches: [],
    adminOpinion: '证书有效，但末页缺少认证机构骑缝章，需要补充后归档。',
    unmetClauses: ['认证证书末页缺少认证机构骑缝章'],
    improvementSuggestions: ['补传完整扫描件', '补充认证机构盖章页'],
    appealable: false,
    appealDeadline: '',
    reviewerName: '采购审核员-周岚',
    reviewedAt: '2026-04-22T15:18:00',
    batchNo: 'BATCH-UP-20260422-01',
    uploadSource: 'admin',
    uploadedByRole: 'admin',
    uploadedByName: '采购审核员-周岚',
  },
  {
    id: 'doc-008',
    taskNo: 'WK-202604-0008',
    supplierId: 'sup-004',
    fileName: '物流装备专利证书-新版.pdf',
    category: 'patent-cert',
    mimeType: 'application/pdf',
    sizeMB: 1.7,
    uploadedAt: '2026-04-23T16:20:00',
    status: 'pending',
    machineStatus: 'pass',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-transport-c-v1',
    extractedFields: {
      enterpriseName: '筋云物流装备（南京）有限公司',
      creditCode: '91320115MA27L2C88P',
      legalPerson: '何嘉恒',
      validUntil: '2028-09-30',
      certificationScope: '物流周转器具结构优化专利',
    },
    comparisons: [
      { field: '企业名称', expected: '筋云物流装备（南京）有限公司', actual: '筋云物流装备（南京）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91320115MA27L2C88P', actual: '91320115MA27L2C88P', result: '匹配' },
      { field: '专利名称', expected: '需与技术申报一致', actual: '物流周转器具结构优化专利', result: '匹配' },
      { field: '证书有效期', expected: '有效', actual: '2028-09-30', result: '匹配' },
    ],
    riskFlags: [],
    externalChecks: [
      {
        id: 'ext-doc-008-1',
        serviceCode: 'ocr-engine',
        serviceName: 'OCR 识别服务',
        checkItem: '专利证书 OCR 识别',
        materialName: '物流装备专利证书-新版.pdf',
        affectedFields: ['专利名称'],
        affectedMaterials: ['物流装备专利证书-新版.pdf'],
        status: 'exception',
        exceptionType: 'partial-result',
        message: 'OCR 返回局部字段缺失，专利名称未形成完整结构化结果。',
        fallbackSuggestion: '请直接查看原始专利证书页面并人工确认专利名称与范围。',
      },
    ],
    precheckScore: 90,
    scoreBreakdown: { quality: 89, technical: 91, business: 88, bonus: 0, total: 90 },
    sameSourceMatches: [],
    adminOpinion: '',
    unmetClauses: [],
    improvementSuggestions: [],
    appealable: false,
    appealDeadline: '',
    reviewerName: '',
    reviewedAt: '',
  },
  {
    id: 'doc-009',
    taskNo: 'WK-202604-0009',
    supplierId: 'sup-001',
    fileName: '质量体系证书-更名说明版.pdf',
    category: 'quality-system',
    mimeType: 'application/pdf',
    sizeMB: 2.9,
    uploadedAt: '2026-04-24T14:12:00',
    status: 'rejected',
    machineStatus: 'fail',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-raw-a-v3',
    extractedFields: {
      enterpriseName: '华锐精密制造（深圳）有限公司（更名前）',
      creditCode: '91440300MA5F8P2K2M',
      legalPerson: '陈泽明',
      validUntil: '2027-09-30',
      certificationScope: '机加工件质量管理体系',
    },
    comparisons: [
      { field: '企业名称', expected: '华锐精密制造（深圳）有限公司', actual: '华锐精密制造（深圳）有限公司（更名前）', result: '不匹配' },
      { field: '统一社会信用代码', expected: '91440300MA5F8P2K2M', actual: '91440300MA5F8P2K2M', result: '匹配' },
      { field: '法人', expected: '陈泽明', actual: '陈泽明', result: '匹配' },
      { field: '证书有效期', expected: '有效', actual: '2027-09-30', result: '匹配' },
    ],
    riskFlags: ['企业名称与工商登记不一致'],
    precheckScore: 78,
    scoreBreakdown: { quality: 78, technical: 80, business: 76, bonus: 0, total: 78 },
    sameSourceMatches: [],
    adminOpinion: '证书主体名称仍显示为更名前企业名称，缺少认证机构出具的主体延续说明函。',
    unmetClauses: ['证书主体名称与当前工商登记信息不一致', '未提供认证机构更名连续性证明'],
    improvementSuggestions: ['补充企业更名证明文件', '补充认证机构出具的主体延续说明函'],
    appealable: true,
    appealDeadline: '2026-05-12T23:59:59',
    appealSceneTitle: '更名过渡期证书主体异议',
    appealSceneSummary: '适用于企业已完成工商更名，但资质证书尚处在旧名称过渡期的申诉场景。',
    reviewerName: '采购审核员-周岚',
    reviewedAt: '2026-04-24T16:40:00',
  },
  {
    id: 'doc-010',
    taskNo: 'WK-202604-0010',
    supplierId: 'sup-001',
    fileName: '补充说明函-采购范围核验.pdf',
    category: 'other',
    mimeType: 'application/pdf',
    sizeMB: 1.6,
    uploadedAt: '2026-04-25T09:35:00',
    status: 'conditional',
    machineStatus: 'warning',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-raw-a-v3',
    extractedFields: {
      enterpriseName: '华锐精密制造（深圳）有限公司',
      creditCode: '91440300MA5F8P2K2M',
      legalPerson: '陈泽明',
      validUntil: '2026-12-31',
      certificationScope: '采购范围补充说明',
    },
    comparisons: [
      { field: '企业名称', expected: '华锐精密制造（深圳）有限公司', actual: '华锐精密制造（深圳）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91440300MA5F8P2K2M', actual: '91440300MA5F8P2K2M', result: '匹配' },
      { field: '说明覆盖范围', expected: '覆盖本次采购件型', actual: '仅覆盖结构件和夹具类', result: '待确认' },
      { field: '文件有效期', expected: '有效', actual: '2026-12-31', result: '匹配' },
    ],
    riskFlags: ['认证范围待核实'],
    precheckScore: 84,
    scoreBreakdown: { quality: 82, technical: 85, business: 84, bonus: 1, total: 84 },
    sameSourceMatches: [],
    adminOpinion: '当前补充说明可作为阶段性留档，但仍需进一步明确是否覆盖全部采购件型。',
    unmetClauses: ['补充说明未覆盖全部采购件型', '缺少最终客户使用场景佐证'],
    improvementSuggestions: ['重新出具覆盖全采购件型的盖章说明', '补充近 6 个月供货佐证或项目清单'],
    appealable: true,
    appealDeadline: '2026-05-14T23:59:59',
    appealSceneTitle: '补充说明充分性申诉',
    appealSceneSummary: '适用于供应商认为现有说明已满足阶段准入要求，希望提交补充业务佐证后申请调整结论。',
    reviewerName: '采购审核员-周岚',
    reviewedAt: '2026-04-25T11:25:00',
  },
  {
    id: 'doc-011',
    taskNo: 'WK-202604-0011',
    supplierId: 'sup-004',
    fileName: '营业执照-管理员批次补档.pdf',
    category: 'business-license',
    mimeType: 'application/pdf',
    sizeMB: 2.1,
    uploadedAt: '2026-04-25T14:42:00',
    status: 'approved',
    machineStatus: 'pass',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-transport-c-v1',
    extractedFields: {
      enterpriseName: '筋云物流装备（南京）有限公司',
      creditCode: '91320115MA27L2C88P',
      legalPerson: '何嘉恒',
      validUntil: '2029-03-31',
      certificationScope: '企业主体经营资格',
    },
    comparisons: [
      { field: '企业名称', expected: '筋云物流装备（南京）有限公司', actual: '筋云物流装备（南京）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91320115MA27L2C88P', actual: '91320115MA27L2C88P', result: '匹配' },
      { field: '法人', expected: '何嘉恒', actual: '何嘉恒', result: '匹配' },
      { field: '证书有效期', expected: '有效', actual: '2029-03-31', result: '匹配' },
    ],
    riskFlags: [],
    precheckScore: 92,
    scoreBreakdown: { quality: 91, technical: 92, business: 93, bonus: 0, total: 92 },
    sameSourceMatches: [],
    adminOpinion: '批量建档补传的营业执照清晰完整，可直接归档。',
    unmetClauses: [],
    improvementSuggestions: [],
    appealable: false,
    appealDeadline: '',
    reviewerName: '采购审核员-周岚',
    reviewedAt: '2026-04-25T15:10:00',
    batchNo: 'BATCH-UP-20260425-01',
    uploadSource: 'admin',
    uploadedByRole: 'admin',
    uploadedByName: '采购审核员-周岚',
  },
  {
    id: 'doc-012',
    taskNo: 'WK-202604-0012',
    supplierId: 'sup-005',
    fileName: '代理授权链路说明函.pdf',
    category: 'other',
    mimeType: 'application/pdf',
    sizeMB: 1.8,
    uploadedAt: '2026-04-26T08:50:00',
    status: 'conditional',
    machineStatus: 'warning',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-trade-b-v1',
    extractedFields: {
      enterpriseName: '启衡工业贸易（苏州）有限公司',
      creditCode: '91320594MA27B6N31K',
      legalPerson: '林岳',
      validUntil: '2026-12-31',
      certificationScope: '代理授权与供应链责任划分',
    },
    comparisons: [
      { field: '企业名称', expected: '启衡工业贸易（苏州）有限公司', actual: '启衡工业贸易（苏州）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91320594MA27B6N31K', actual: '91320594MA27B6N31K', result: '匹配' },
      { field: '授权链路', expected: '覆盖品牌方至代理商全链路', actual: '缺少末级授权签章', result: '待确认' },
      { field: '文件有效期', expected: '有效', actual: '2026-12-31', result: '匹配' },
    ],
    riskFlags: ['认证范围待核实'],
    externalChecks: [
      {
        id: 'ext-doc-012-1',
        serviceCode: 'business-registry',
        serviceName: '工商信息核验接口',
        checkItem: '主体工商比对',
        materialName: '代理授权链路说明函.pdf',
        affectedFields: ['企业名称', '统一社会信用代码'],
        affectedMaterials: ['代理授权链路说明函.pdf'],
        status: 'exception',
        exceptionType: 'service-unavailable',
        message: '工商核验接口调用失败，本次未返回主体比对结果。',
        fallbackSuggestion: '请人工核对授权主体、营业执照和系统主数据是否一致。',
      },
    ],
    precheckScore: 83,
    scoreBreakdown: { quality: 82, technical: 80, business: 86, bonus: 1, total: 83 },
    sameSourceMatches: [],
    adminOpinion: '授权链路基本完整，但末级代理授权签章缺失，先保留结果并要求补齐。',
    unmetClauses: ['末级代理授权签章缺失'],
    improvementSuggestions: ['补充品牌方到末级代理完整盖章链路', '补充责任分界附件'],
    appealable: false,
    appealDeadline: '',
    reviewerName: '',
    reviewedAt: '',
  },
  {
    id: 'doc-013',
    taskNo: 'WK-202604-0013',
    supplierId: 'sup-006',
    fileName: '安全责任承诺函-管理员批次上传.pdf',
    category: 'other',
    mimeType: 'application/pdf',
    sizeMB: 1.4,
    uploadedAt: '2026-04-25T15:02:00',
    status: 'approved',
    machineStatus: 'pass',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-other-c-v1',
    extractedFields: {
      enterpriseName: '安澄环境服务（重庆）有限公司',
      creditCode: '91500112MA61P8F54L',
      legalPerson: '顾岩',
      validUntil: '2027-12-31',
      certificationScope: '驻场服务安全责任承诺',
    },
    comparisons: [
      { field: '企业名称', expected: '安澄环境服务（重庆）有限公司', actual: '安澄环境服务（重庆）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91500112MA61P8F54L', actual: '91500112MA61P8F54L', result: '匹配' },
      { field: '责任承诺范围', expected: '覆盖驻场服务与安全责任', actual: '覆盖驻场服务与安全责任', result: '匹配' },
      { field: '文件有效期', expected: '有效', actual: '2027-12-31', result: '匹配' },
    ],
    riskFlags: [],
    precheckScore: 88,
    scoreBreakdown: { quality: 87, technical: 84, business: 90, bonus: 1, total: 88 },
    sameSourceMatches: [],
    adminOpinion: '综合服务类承诺函已纳入批量建档，内容符合模板要求。',
    unmetClauses: [],
    improvementSuggestions: [],
    appealable: false,
    appealDeadline: '',
    reviewerName: '采购审核员-周岚',
    reviewedAt: '2026-04-25T15:36:00',
    batchNo: 'BATCH-UP-20260425-01',
    uploadSource: 'admin',
    uploadedByRole: 'admin',
    uploadedByName: '采购审核员-周岚',
  },
  {
    id: 'doc-014',
    taskNo: 'WK-202604-0014',
    supplierId: 'sup-006',
    fileName: '驻场服务安全责任函-补传版.pdf',
    category: 'other',
    mimeType: 'application/pdf',
    sizeMB: 1.5,
    uploadedAt: '2026-04-26T08:58:00',
    status: 'pending',
    machineStatus: 'warning',
    previewUrl: SAMPLE_PDF_DATA_URI,
    standardTemplateId: 'std-other-c-v1',
    extractedFields: {
      enterpriseName: '安澄环境服务（重庆）有限公司',
      creditCode: '91500112MA61P8F54L',
      legalPerson: '顾岩',
      validUntil: '2027-12-31',
      certificationScope: '驻场服务安全责任补充承诺',
    },
    comparisons: [
      { field: '企业名称', expected: '安澄环境服务（重庆）有限公司', actual: '安澄环境服务（重庆）有限公司', result: '匹配' },
      { field: '统一社会信用代码', expected: '91500112MA61P8F54L', actual: '91500112MA61P8F54L', result: '匹配' },
      { field: '补传内容', expected: '补充风险处置职责边界', actual: '补充到现场作业部分', result: '待确认' },
      { field: '文件有效期', expected: '有效', actual: '2027-12-31', result: '匹配' },
    ],
    riskFlags: ['补传资料待确认'],
    precheckScore: 85,
    scoreBreakdown: { quality: 84, technical: 83, business: 87, bonus: 1, total: 85 },
    sameSourceMatches: [],
    adminOpinion: '',
    unmetClauses: [],
    improvementSuggestions: [],
    appealable: false,
    appealDeadline: '',
    reviewerName: '',
    reviewedAt: '',
  },
]

export const MOCK_APPEALS = [
  {
    id: 'apl-001',
    recordId: 'doc-005',
    supplierId: 'sup-001',
    supplierName: '华锐精密制造（深圳）有限公司',
    fileName: '行业强制认证-补充说明版.pdf',
    status: 'supplement_required',
    reasonType: 'scope',
    title: '申请确认补充说明已覆盖采购范围',
    summary: '供应商认为现有盖章说明已能够覆盖本次采购产品范围，请求将结论调整为通过。',
    description:
      '我们已重新整理行业强制认证的补充说明，并补充了最近 6 个月的供货清单。由于原盖章附件扫描件不完整，先前页面未显示完整说明，本次申诉希望结合补传材料重新判定。',
    requestedOutcome: '希望将当前“有条件通过”调整为“通过”，或明确仅需补充单一附件即可归档。',
    contactPhone: '13800138000',
    evidenceNotes: '已补充历史供货佐证、认证机构盖章附件、采购件型覆盖说明。',
    attachments: [
      { id: 'apl-file-001', name: '供货范围补充说明-盖章版.pdf', type: 'application/pdf', sizeMB: 1.8 },
      { id: 'apl-file-002', name: '近六个月供货项目清单.xlsx', type: 'application/vnd.ms-excel', sizeMB: 0.6 },
    ],
    assigneeName: '采购审核员 周岚',
    assignedAt: '2026-04-20T14:05:00',
    submittedAt: '2026-04-19T10:12:00',
    updatedAt: '2026-04-21T15:20:00',
    latestFeedback: '管理员已受理，当前要求补充更清晰的盖章页扫描件后继续复核。',
    timeline: [
      {
        id: 'apl-log-001',
        at: '2026-04-19T10:12:00',
        actor: '供应商',
        action: '提交申诉',
        note: '提交补充说明、供货范围佐证和盖章附件。',
      },
      {
        id: 'apl-log-002',
        at: '2026-04-20T14:05:00',
        actor: '管理员',
        action: '受理申诉',
        note: '进入复核队列，待采购审核员补充核验。',
      },
      {
        id: 'apl-log-003',
        at: '2026-04-21T15:20:00',
        actor: '管理员',
        action: '要求补充材料',
        note: '当前扫描件盖章边缘不清晰，请补充更高清版本。',
      },
    ],
  },
  {
    id: 'apl-002',
    recordId: 'doc-003',
    supplierId: 'sup-002',
    supplierName: '鼎衡供应链科技（上海）有限公司',
    fileName: '专利证书-信息不一致.png',
    status: 'accepted',
    reasonType: 'entity',
    title: '专利证书主体名称已完成更正',
    summary: '供应商补充了更名后的专利证书和工商变更证明，请求撤销未通过结论。',
    description:
      '原上传文件使用的是旧版专利证书截图，后续已完成证书主体名称更新，并同步上传工商变更证明及新版证书，申请恢复审核通过。',
    requestedOutcome: '将当前未通过记录调整为通过，并保留申诉通过说明。',
    contactPhone: '13922334455',
    evidenceNotes: '新版专利证书、工商变更证明、认证主体连续性说明。',
    attachments: [
      { id: 'apl-file-003', name: '新版专利证书.pdf', type: 'application/pdf', sizeMB: 1.2 },
      { id: 'apl-file-004', name: '工商变更证明.pdf', type: 'application/pdf', sizeMB: 0.9 },
    ],
    assigneeName: '采购审核员 周岚',
    assignedAt: '2026-04-15T13:40:00',
    submittedAt: '2026-04-14T09:18:00',
    updatedAt: '2026-04-16T18:10:00',
    latestFeedback: '申诉成立，管理员已确认主体名称更新完成。',
    timeline: [
      {
        id: 'apl-log-004',
        at: '2026-04-14T09:18:00',
        actor: '供应商',
        action: '提交申诉',
        note: '提交新版专利证书与变更证明。',
      },
      {
        id: 'apl-log-005',
        at: '2026-04-15T13:40:00',
        actor: '管理员',
        action: '复核中',
        note: '已核对证书主体名称与工商数据。',
      },
      {
        id: 'apl-log-006',
        at: '2026-04-16T18:10:00',
        actor: '管理员',
        action: '申诉通过',
        note: '确认更名连续性成立，申诉结案。',
      },
    ],
  },
  {
    id: 'apl-003',
    recordId: 'doc-012',
    supplierId: 'sup-005',
    supplierName: '启衡工业贸易（苏州）有限公司',
    fileName: '代理授权链路说明函.pdf',
    status: 'under_review',
    reasonType: 'authorization',
    title: '代理授权链路完整性复核申请',
    summary: '供应商认为末级授权签章已在补充页体现，请求复核有条件通过结论。',
    description:
      '我们已重新整理品牌方到末级代理的授权链路，并补充了盖章页顺序说明。由于原文件拆分上传导致信息分散，本次申请合并材料后重新核定。',
    requestedOutcome: '保留准入资格并尽快完成复核，如仍需补件请明确缺失节点。',
    contactPhone: '13588997766',
    evidenceNotes: '已合并授权链路、责任分界说明和末级代理盖章页。',
    attachments: [
      { id: 'apl-file-005', name: '完整代理授权链路.pdf', type: 'application/pdf', sizeMB: 2.3 },
    ],
    assigneeName: '',
    assignedAt: '',
    submittedAt: '2026-04-26T10:05:00',
    updatedAt: '2026-04-26T14:30:00',
    latestFeedback: '申诉已提交，等待采购审核员分派复核。',
    timeline: [
      {
        id: 'apl-log-007',
        at: '2026-04-26T10:05:00',
        actor: '供应商',
        action: '提交申诉',
        note: '提交完整代理授权链路及盖章页。',
      },
      {
        id: 'apl-log-008',
        at: '2026-04-26T14:30:00',
        actor: '系统',
        action: '进入复核队列',
        note: '已通知管理员进入待复核状态。',
      },
    ],
  },
]

